# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StudentSublease_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StudentSublease_iOS
pod 'MessageKit'

  target 'StudentSublease_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudentSublease_iOSUITests' do
    # Pods for testing
  end

end
